### ISSUE TITLE
wrong run: stage_one.py, line 71, in count_16s

### ISSUE THREAD

**Issue by Wang2093** [xinehc/args_oap#14]
When I run
args_oap stage_one -i */arg_fasta/ -o */MGE_one/ -f fa -t 40
I got
Processing <*/arg_fasta/AO487-S01-01R0001_1.fa> (1/2) ...
Traceback (most recent call last):
  File "*/miniconda3/envs/args_oap/bin/args_oap", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "*/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/args_oap.py", line 91, in main
    options.func(options)
  File "*/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_one.py", line 203, in run_stage_one
    StageOne(vars(options)).run()
  File "*/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_one.py", line 188, in run
    n16S=self.count_16s(file)
         ^^^^^^^^^^^^^^^^^^^^
  File "*/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_one.py", line 71, in count_16s
    subp = subprocess.run(['bwa', 'mem', '-t', str(self.thread), settings._gg85, file], check=True, capture_output=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*/miniconda3/envs/args_oap/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwa', 'mem', '-t', '40', '*/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/db/gg85.fasta', '*/arg_fasta/AO487-S01-01R0001_1.fa']' returned non-zero exit status 1.
Can you help me?

**Comment by Wang2093** [comment]
It is a nucleotide fasta file.
I re-install the args_oap and it works well now.
There must be something wrong happened that overlooked by me when I install it.
Thanks very much.  @Xinehc
