### ISSUE TITLE
ARGs Desktop运行个性化数据库失败问题

### ISSUE THREAD

**Issue by fengyuan1112** [xinehc/args_oap#33]
首先，十分感谢贵课题组的ARGs-OAP给我们这种生信刚入门的小白提供了研究ARG的便利工具，我最近在尝试使用Desktop版本（windows）进行个性化数据库分析，已经成功使用Ncyc等多种数据库进行分析，但是当使用同样的方法进行Nature文章中所提供的MGEs数据库进行分析时，总是会出现如下错误，恳请您们帮忙指点迷津，十分感谢
[2023-07-25 00:13:06,443] [INFO] Calling args_oap/stage_one with ['stage_one', '--indir', 'D:\\Metagenomics\\ARGs-OAP\\input\\test_P', '--outdir', 'D:\\Metagenomics\\ARGs-OAP\\input\\test', '--thread', '2', '--format', 'fa', '--skip', '--database', 'D:\\Metagenomics\\ARGs-OAP\\MGEs\\MobileGeneticElementDatabase-master\\MGEs_FINAL_99perc_trim.fasta']
[2023-07-25 00:13:06,457] [INFO] Building databases ...
[2023-07-25 00:13:20,312] [INFO] Processing <D:\Metagenomics\ARGs-OAP\input\test_P\E1_final.contigs.fa> (1/1) ...
[2023-07-25 00:15:35,473] [ERROR] Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\interface.py", line 474, in start_new_job
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\modules\args_oap\api.py", line 77, in call_stage_one
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\modules\args_oap\stage_one.py", line 210, in run_stage_one
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\modules\args_oap\stage_one.py", line 190, in run
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\modules\args_oap\stage_one.py", line 172, in extract_seqs
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 548, in run
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 1024, in __init__
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 1509, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

[2023-07-25 00:15:35,473] [ERROR] FileNotFoundError(2, '系统找不到指定的文件。', None, 2, None), please check whether you have installed necessary modules.

**Comment by xinehc** [comment]
Hi,

this could be caused by missing certain binaries or incompatibility in Windows, will try to fix but it may take some time, please use the command line version for customised nucleotide database ATM.

**Comment by fengyuan1112** [comment]
非常感谢您百忙之中抽出时间为我解答疑惑，我会根据您的建议继续进行相关尝试，也非常期待您们的软件能够更加完善
