### ISSUE TITLE
比对结束第一步，然后第二步，显示这个，如何解决

### ISSUE THREAD

**Issue by pl19940314** [xinehc/args_oap#63]
Error: Unknown argument: "mt_mode"
Error:  (CArgException::eInvalidArg) Unknown argument: "mt_mode"
Traceback (most recent call last):
  File "/home/meta/miniconda3/envs/args_oap/bin/args_oap", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/args_oap.py", line 97, in main
    options.func(options)
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_two.py", line 190, in run_stage_two
    StageTwo(vars(options)).run()
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_two.py", line 185, in run
    self.extract_seqs()
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/stage_two.py", line 115, in extract_seqs
    subprocess.run(cmd, check=True)
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['blastx', '-db', '/home/meta/miniconda3/envs/args_oap/lib/python3.11/site-packages/args_oap/db/sarg.fasta', '-query', '/home/meta/mdisk/pl/soil/soil_fasta/L1HHK01/L1HHK01_args/extracted.fa', '-out', '/home/meta/mdisk/pl/soil/soil_fasta/L1HHK01/L1HHK01_args/blastout.txt', '-outfmt', '6 qseqid sseqid pident length qlen slen evalue bitscore', '-evalue', '1e-07', '-max_target_seqs', '5', '-num_threads', '5', '-mt_mode', '0']' returned non-zero exit status 1.

**Comment by xinehc** [comment]
Hi,

you may consider upgrading blast to >=2.12. 

Reference: https://blast.ncbi.nlm.nih.gov/doc/blast-news/2021-BLAST-News.html
