### ISSUE TITLE
this software had met mistake, i had changed the blastn version, diamond version， how can i solve it ?

### ISSUE THREAD

**Issue by pl19940314** [xinehc/args_oap#65]
WARNING: Output folder </home/meta/mdisk/pl/earthworm/megahit/cd-hit/L1HHH0200300/MGE_new> contains <blastout.txt> and/or <*.filtered.*>, they/it will be overwritten.
[2024-05-09 14:50:21] INFO: Processing </home/meta/mdisk/pl/earthworm/megahit/cd-hit/L1HHH0200300/MGE_new/extracted.fa> ...
[2024-05-09 14:50:21] INFO: Extracting target sequences using BLAST ...
[2024-05-09 14:50:21] INFO: BLAST settings: 1260675 bps, 8355 reads, 10 threads, mt_mode 0.
[2024-05-09 14:50:24] INFO: Merging files ...
Traceback (most recent call last):
  File "/home/meta/miniconda3/envs/args_oap/bin/args_oap", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/args_oap/args_oap.py", line 232, in main
    options.func(options)
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/args_oap/stage_two.py", line 213, in run_stage_two
    StageTwo(vars(options)).run()
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/args_oap/stage_two.py", line 208, in run
    self.merge_files()
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/args_oap/stage_two.py", line 191, in merge_files
    out = pd.merge(self.metadata, result, on='sample')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 170, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 794, in __init__
    ) = self._get_merge_keys()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1310, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/miniconda3/envs/args_oap/lib/python3.12/site-packages/pandas/core/generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'sample'

**Comment by xinehc** [comment]
Did you modified the `metadata.txt` file?

Can you confirm that the first entry of the file is `sample` using:
 ```
grep sample metadata.txt
```

**Comment by pl19940314** [comment]
![image](https://github.com/xinehc/args_oap/assets/19246543/1d0225bf-afd1-4ab8-beb8-8ecfcea9ee28)

**Comment by pl19940314** [comment]
i have rerun the stage_one, after, the stage_two had not make mistake and had sucessfully run again
