### ISSUE TITLE
UnboundLocalError: local variable 'dbtype' referenced before assignment

### ISSUE THREAD

**Issue by tenethe** [xinehc/args_oap#66]
Hei,

Many thanks to the developers. I installed args_oap in a container environment (tykky). When I ran stage_one for the example fasta files, an issue occurred. Was the error due to the environment? May I ask if there is any solution for this? Thank you. 

$ args_oap stage_one -i input -o output -f fa -t 8
[2024-06-03 15:44:15] INFO: Building databases ...
Traceback (most recent call last):
  File "/*/tykky-env/bin/args_oap", line 10, in <module>
    sys.exit(main())
  File "/*/python3.10/site-packages/args_oap/args_oap.py", line 232, in main
    options.func(options)
  File "/*/python3.10/site-packages/args_oap/stage_one.py", line 229, in run_stage_one
    StageOne(vars(options)).run()
  File "/*/python3.10/site-packages/args_oap/stage_one.py", line 62, in __init__
    make_db(file)
  File "/*/python3.10/site-packages/args_oap/make_db.py", line 42, in make_db
    '-dbtype', dbtype,
UnboundLocalError: local variable 'dbtype' referenced before assignment

**Comment by xinehc** [comment]
Hi,

it is likely you do not have the write permission to path `/*/python3.10/site-packages/args_oap/`.

**Comment by tenethe** [comment]
> Hi,
> 
> it is likely you do not have the write permission to path `/*/python3.10/site-packages/args_oap/`.

Thanks so much for your reply. It seems that the path has been hidden in the container, and we don't have the access permission. I will contact the admin soon. Alternatively, I tried the windows version, but there are also some issues:

[2024-06-06 12:17:53,494] [INFO] Calling args_oap/stage_one with ['stage_one', '--indir', 'C:\\Users\\Downloads\\example.tar\\example\\example\\input', '--outdir', 'C:\\Users\\AppData\\Roaming\\args-desktop\\output\\args_oap_edf5', '--thread', '4', '--format', 'fa', '--e2', '3']
[2024-06-06 12:17:53,504] [INFO] Processing <C:\Users\Downloads\example.tar\example\example\input\STAS_1.fa> (1/4) ...
[2024-06-06 12:18:10,491] [WARNING] No 16S-like sequences found in file <C:\Users\Downloads\example.tar\example\example\input\STAS_1.fa>.
[2024-06-06 12:18:22,613] [INFO] Processing <C:\Users\Downloads\example.tar\example\example\input\STAS_2.fa> (2/4) ...
[2024-06-06 12:18:40,484] [ERROR] C:\Users\AppData\Local\Temp\ONEFIL~1\interface.py 474 CalledProcessError(1, ['bwa', 'mem', '-t', '4', 'C:\\Users\\AppData\\Local\\Temp\\onefile_22260_133621389485638375\\resources\\args_oap\\db\\gg85.fasta', 'C:\\Users\\Downloads\\example.tar\\example\\example\\input\\STAS_2.fa'])

[2024-06-06 12:16:34,466] [INFO] Calling args_oap/stage_one with ['stage_one', '--indir', 'C:\\Users\\Downloads\\example.tar\\example\\example\\input', '--outdir', 'C:\\Users\\AppData\\Roaming\\args-desktop\\output\\args_oap_IGXv', '--thread', '4', '--format', 'fa', '--e2', '3']
[2024-06-06 12:16:34,478] [INFO] Building databases ...
[2024-06-06 12:16:40,675] [INFO] Processing <C:\Users\Downloads\example.tar\example\example\input\STAS_1.fa> (1/4) ...
[2024-06-06 12:16:55,061] [ERROR] C:\Users\AppData\Local\Temp\ONEFIL~1\interface.py 519 CalledProcessError(1, ['bwa', 'mem', '-t', '4', 'C:\\Users\\AppData\\Local\\Temp\\onefile_22260_133621389485638375\\resources\\args_oap\\db\\gg85.fasta', 'C:\\Users\\Downloads\\example.tar\\example\\example\\input\\STAS_1.fa'])

Did you see these issues before? Thank you.

**Comment by chaoyanggu** [comment]
Hi,
I downloaded the SARG database from the URL: https://smile.hku.hk/ARGs/dataset/indexingdownload/Short_subdatabase_V3.2.1.zip, and successfully built the database index.
args_oap make_db -i 4.SARG_v3.2_20220917_Short_subdatabase.fasta

Then I ran the following command:
args_oap stage_one -i MECOS_2023_200/ -o output/ -f fq --database 4.SARG_v3.2_20220917_Short_subdatabase.fasta
But I encountered an error and couldn't resolve it. Here is the error message:

[2025-10-30 16:29:33] INFO: Building databases ...
Traceback (most recent call last):
  File "/datapool/software/anaconda3/envs/kofamscan/bin/args_oap", line 33, in <module>
    sys.exit(load_entry_point('args-oap==3.2.4', 'console_scripts', 'args_oap')())
  File "/datapool/software/anaconda3/envs/kofamscan/lib/python3.9/site-packages/args_oap-3.2.4-py3.9.egg/args_oap/args_oap.py", line 232, in main
    options.func(options)
  File "/datapool/software/anaconda3/envs/kofamscan/lib/python3.9/site-packages/args_oap-3.2.4-py3.9.egg/args_oap/stage_one.py", line 229, in run_stage_one
    StageOne(vars(options)).run()
  File "/datapool/software/anaconda3/envs/kofamscan/lib/python3.9/site-packages/args_oap-3.2.4-py3.9.egg/args_oap/stage_one.py", line 62, in __init__
    make_db(file)
  File "/datapool/software/anaconda3/envs/kofamscan/lib/python3.9/site-packages/args_oap-3.2.4-py3.9.egg/args_oap/make_db.py", line 42, in make_db
    '-dbtype', dbtype,
UnboundLocalError: local variable 'dbtype' referenced before assignment

I had the write permissions to the database. I hope to get your help. Thank you.
