### ISSUE TITLE
Unable to download results

### ISSUE THREAD

**Issue by esraagithub** [xinehc/args_oap#8]
Hello
I uploaded my fasta and metadata.txt files into the online pipeline v 2.2
The process completed in one second, i am not able to download my data when i press the button download, nothing happen

![Screenshot_2022-08-20-14-47-43-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/53595110/185749559-7ae60cbf-7a08-45f0-a0e7-ed3bc727a4bd.jpg)

**Comment by esraagithub** [comment]
when i tried to do stage-2 on command line. i got this error:


 File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CellNumber'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/esraa/miniconda3/envs/args_oap/lib/python3.10/site-packages/args_oap/argoap_pipeline_stagetwo_version3.py", line 177, in <module>
    result1_type["percell"] = result1_type["ratio"] / result1_type["CellNumber"]
  File "/root/esraa/miniconda3/envs/args_oap/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/esraa/miniconda3/envs/args_oap/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'CellNumber'

**Comment by xinehc** [comment]
Hi,

Is column 'CellNumber' in your meta-data-online.txt empty? Did you try to run both stageone and stagetwo locally using the latest version of args_oap (>3.0)?

Xi

**Comment by esraagithub** [comment]
> 

> Hi,
> 
> Is column 'CellNumber' in your meta-data-online.txt empty? Did you try to run both stageone and stagetwo locally using the latest version of args_oap (>3.0)?
> 
> Xi

I used bioconda version beta
Cell number column is not empty
![IMG_٢٠٢٢٠٨٢٣_١٢٥٥١٦](https://user-images.githubusercontent.com/53595110/186140988-5b8b9563-7ad6-4838-a965-e9fb11700ade.jpg)

**Comment by esraagithub** [comment]
**Metadata** for stage one doesn't contain Cell number because i don't now cell number in this metagenomic data. **Metadata_online** for stage two has Cell number
Should i add 'cell number' column in the first metadata file (for stage one) and leave its cells empty?

**Comment by xinehc** [comment]
> `Should i add 'cell number' column in the first metadata file (for stage one) and leave its cells empty?`

No, this is not needed. 

What command did you use for stagetwo? Is parameter `-m meta-data.txt` or `-m meta-data-online.txt`?

**Comment by esraagithub** [comment]
-m Metadata_online.txt which which i attached its screenshot above

في الأربعاء، ٢٤ أغسطس ٢٠٢٢ ٩:٥٠ ص Xi Chen ***@***.***> كتب:

**Comment by priscillaisaac98** [comment]
Similar issue encountered.
I uploaded my fasta and metadata.txt files into the online pipeline v 2.2
The process completed in one second, i am not able to download my data when i press the button download, nothing happen

Is there something wrong with the webserver?
